### ISSUE TITLE
Path dei file da compilare

### ISSUE THREAD

**Issue by carlodefalco** [PatrickPenzo70/Esame-PACS#1]
qui:

https://github.com/PatrickPenzo70/Esame-PACS/blob/a167964ff35d2d26c259024cedb0d66d4006e87e/Makefile#L4

indichi che i file da compilare sono nella sottocartella `src` che però non esiste, quindi la compilazione non funziona perché i file non vengono trovati.

O cambi il `Makefile` o sposti i file.

Inoltre, così com'è strutturato il `Makefile`, se cambi uno degli header il codice non viene ricompilato.

**Comment by PatrickPenzo70** [comment]
Si si nel pc sono all’interno delle cartelle scr include … ma non si compila comunque.
Sarà per il secondo motivo.

________________________________
Da: carlodefalco ***@***.***>
Inviato: martedì 22 ottobre 2024 09:38
A: PatrickPenzo70/Esame-PACS ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [PatrickPenzo70/Esame-PACS] Path dei file da compilare (Issue #1)


qui:

https://github.com/PatrickPenzo70/Esame-PACS/blob/a167964ff35d2d26c259024cedb0d66d4006e87e/Makefile#L4

indichi che i file da compilare sono nella sottocartella src che però non esiste, quindi la compilazione non funziona perché i file non vengono trovati.

O cambi il Makefile o sposti i file.

Inoltre, così com'è strutturato il Makefile, se cambi uno degli header il codice non viene ricompilato.

**Comment by carlodefalco** [comment]
suggerimento : 

https://github.com/PatrickPenzo70/Esame-PACS/blob/a167964ff35d2d26c259024cedb0d66d4006e87e/Makefile#L10

dove sta scritto quali sono i file sorgente da compilare?

suggerimento più generale, prima di inserire un comando nel makefile provalo da linea di comando e vedi se funziona, quale comando useresti da linea di comand?

ultimo suggerimento la tua copia locale e quella su github devono essere sempre sincronizzate, se in locale hai una cartella e su github no, il repository non ti serve a niente!

**Comment by carlodefalco** [comment]
> Il giorno 22 ott 2024, alle ore 23:45, Patrick Penzo <patrick.penzo@polimi.it> ha scritto:
> tornando al github 
> si possono sincronizzare tutti i file all'interno di una cartella contemporaneamente ? giusto? 

mantieni la discussione nel forum, compila le risposte direttamente dal forum usando questo link : 
https://github.com/PatrickPenzo70/Esame-PACS/issues

i comandi per la sincronizzazione dei file sono : 
* `git push` per sincronizzare il repository remoto con il tuoo repository locale
* `git pull` per sincronizzare il tuo repository locale con quello remoto
* `git clone` per creare una nuova copia locale di un repository remoto

la documentazione di questi comandi la puoi vedere da terminale scrivendo 

```
man git-pull
man git-push
man git-clone
```

oppure dal sito di git : https://git-scm.com/doc 

oppure dal sito di github, in particolare qui : https://education.github.com/git-cheat-sheet-education.pdf

c'è un riassunto dei comandi fondamentali.

Io consiglio di : 

* creare un nuovo repository locale clonando quello remoto (`git clone`)
* spostare i file dove vuoi nel nuovo repository locale (`git mv`) ma non è obbligatotorio, per ora puoi anche tenere tutto nella stessa cartella per semplificare
* fare le modifiche che vuoi in locale e registrarle in git (`git add`, `git commit`)
* sincronizzare il repository remoto con quello locale (`git push`)

c.

**Comment by carlodefalco** [comment]
Avendo ora tutti i file nella stessa cartella, il path non è più un problema.
C'è ancora qualcosa che non va secondo me però : 

https://github.com/PatrickPenzo70/Esame-PACS/blob/54de42d123cdf256499347503d7950a360d0e961/Makefile#L4-L5

I file ```Main.cpp Balls.cpp Collision.cpp Configuration.cpp Flow.cpp Simulation.cpp``` sono elencati fra le dipendenze ma non vengono usati nel comando di compilazione, quindi o non servono o il comando non è corretto

Il file ```Balls-in-poiseuille-fluids-with-oneself-collisions.cpp``` è usato nel comando di compilazione ma non è fra le dipendenze, quindi o è il file sbagliato o va aggiunto fra le dipendenze, inoltre non è nel repository quindi se è necessario va aggiunto, altrimenti non si può compilare niente

**Comment by PatrickPenzo70** [comment]
Aggiunto il file Balls-in-poiseuille-fluids-with-oneself-collisions.cpp fra le dipendenze e nella repository
